- .github/workflows/backport.yaml
- .github/workflows/go-checks.yaml
- .github/workflows/jira.yaml
- CODEOWNERS
The gofumpt and go.mod tidy checks were tested on a repository.
I also added some usage instructions for the JIRA sync, and did a simple test, though I was not able to test the whole action completely yet.
For backports, I wrote something that might work, but when I tried to test it, it always failed with:
```
2023/03/01 23:18:39 backport-assistant error: error while applying
environment option in New: error while authenticating with GitHub:
GET https://api.github.com/user: 403 Resource not accessible by integration []
```
I don't think we use the backport flow that often for plugins, so it may not get used. (And even so, it is only a single step, so it isn't terrible to copy-paste, if we can figure out the permissions issue).
I did not do add a reusable check for the changelog, as I'm …
> Add go-checks reusable workflow

- .github/workflows/jira.yaml
I am not sure if this is correct but I don't get an error from actionlint with this change.
Actionlint was reporting:
```
.github/workflows/jira.yaml:62:0: could not parse as YAML: yaml: line 62: did not find expected alphabetic or numeric character [yaml-syntax]
|
62 |       if: !(github.event.pull_request && contains(github.event.pull_request.labels.*.name, 'dependencies')) && (github.event.action == 'opened' || github.event.action == 'created')
|
```
See https://github.com/hashicorp/vault-plugin-database-couchbase/actions/runs/4472797426
> fix jira if syntax

- .github/workflows/bulk-dependency-updates.yaml
We should only need one token. Also, Commits were being [made by the github-actions user](https://github.com/hashicorp/vault-plugin-database-snowflake/pull/42/commits/d25f1ffc0b8a2cc0eb9b7637e6ce6882aa685383) but this resulted in the [CLA not-signed block](https://github.com/hashicorp/vault-plugin-database-snowflake/pull/42). So we set the token at the job level.
> set the token at the job level

- .github/workflows/bulk-dependency-updates.yaml
PR's are blocked due to the default github user not having signed the CLA. This was due to setting that user in the git config. This PR should fix that.
> bulk updgrades: use correct user for authenticated commit & push steps

- .github/workflows/jira.yaml
Fixes a parsing error with jq. See the preprocess step here: https://github.com/hashicorp/vault-plugin-auth-alicloud/actions/runs/4744847578/jobs/8426327931
Also, hopefully makes this a little more robust. I tested with the following combinations:
```
| ["ecosystem", "applications", "foundations"]
| ==> Determining team labels
| ==> Found deprecated team label "applications", overwriting with "applications-eco"
| ==> Found deprecated team label "foundations", overwriting with "foundations-eco"
| ==> Using labels: ["applications-eco","foundations-eco"]
| ["ecosystem", "foundations"]
| ==> Determining team labels
| ==> Found deprecated team label "foundations", overwriting with "foundations-eco"
| ==> Using labels: ["foundations-eco"]
| ["ecosystem", "applications"]
| ==> Determining team …
```
> jira sync: fix jq parse error

- .github/workflows/jira.yaml
See the error here: https://github.com/hashicorp/vault-plugin-database-snowflake/actions/runs/4746063918/jobs/8429223968?pr=48 in "Create ticket". The github output wasn't getting set.
I tested this locally with `act` that `echo '${{ steps.preprocess.outputs.teams_array }}'` will output the value we expect.
3rd time is a charm?
> jira sync: step output parse error

- .github/workflows/bulk-dependency-updates.yaml
- .github/workflows/go-checks.yaml
- .github/workflows/tests.yaml
* Consistently use `go-version-file` for all `setup-go` usage. We don't currently provide `go_version` as an input for any existing usages, so I deleted that input option too: https://github.com/search?q=org%3Ahashicorp+hashicorp%2Fvault-workflows-common%2F.github%2Fworkflows%2Fgo-checks.yaml&type=code
* `cache` defaults to true from v4.0.0: https://github.com/actions/setup-go/releases/tag/v4.0.0
* Also update gofumpt to the latest version.
> Ensure setup-go consistently uses go-version-file input

- .github/workflows/actionlint.yaml
- .github/workflows/copyright-headers.yaml
- .github/workflows/go-checks.yaml
Simple reminder check to help reduce the number of follow-up PRs we need for copyright headers.
See https://github.com/hashicorp/vault-csi-provider/pull/208 for an example usage and testing before and after fixing the headers.
Also pins the actionlint docker image we use, and fixes a comment.
> Add copyright headers check

- .github/workflows/actionlint.yaml
actionlint runs are failing. See: https://github.com/hashicorp/vault-plugin-secrets-alicloud/actions/runs/4862741913/jobs/8669514349?pr=84
I think we should be using `latest` as per https://github.com/hashicorp/GHA-migration/blob/main/docs/configure_linting.md
> Update actionlint.yaml to use latest

- LICENSE
Hey folks! 👋 
[Copywrite](https://github.com/hashicorp/copywrite) audits happened to be erroring out for this repo. Upon further investigation, it looks like some portions of the MPL-2.0 license text were inadvertently missing, so this PR adds them back in.
You can regenerate the contents of this PR by removing the `LICENSE` file and running Copywrite locally:
```
copywrite license --spdx MPL-2.0
```
Cheers!
> Fix MPL-2.0 License Text

- .github/workflows/bulk-dependency-updates.yaml
- .github/workflows/dispatch-vault-ci.yaml
This PR adds a step to the plugin dependency workflow that calls a workflow added on the vault side, which itself creates a PR (and triggers a CI workflow). That workflow adds a link to the PR created in _this_ workflow, so a reviewer can easily see whether that workflow passed.
This dispatch can be tested by updating the `uses` reference in a plugin workflow to point to the `@add-update-plugin-check-workflow` reference instead of `@main`
We could also think about making this a separate workflow, and piecemeal update plugin workflows to call this one instead of the original, as we feel it is appropriate.
> Add dispatch to vault workflow to create a vault-side PR for build cross-checks

- .github/workflows/bulk-dependency-updates.yaml
Workflows that call reusable workflows do not have all of the reusable workflow's content. It must be explicitly checked out or fetched from the calling workflow.
> bulk dep updates: fix go-mod-changelog call

- .github/workflows/jira.yaml
I removed `!(github.event.pull_request && contains(github.event.pull_request.labels.*.name, 'dependencies'))` since the `if` expression was getting unwieldy and `github.actor != 'dependabot[bot]'` is sufficient for checking the source is dependabot.
> jira-sync: don't create issue when branch references jira issue

- .github/workflows/jira.yaml
#42 seems to have caused issue comments on GH to create a Jira ticket: https://github.com/hashicorp/terraform-provider-vault/actions/runs/6576373475/job/17865618751
Re-adding back some of the previous checks.
> jira-sync: re-add removed create ticket validation

- .github/workflows/jira.yaml
Fixes two issues:
* `${{ }}` syntax in the middle of the expression was causing it to always evaluate to true. I _think_ this is because it meant it was evaluating the condition inside the brackets and then outside evaluating the result as a truth-y string
* Uses `github.head_ref` instead of `github.ref` for the branch check. The [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) don't make it 100% clear (For workflows triggered by `pull_request`, this is the pull request merge branch), but in my testing, `github.ref` referred to the branch being merged to, aka `github.base_ref` except with the `refs/heads/` prefix, and `github.head_ref` is the branch that the changes are coming from.
> Fix jira sync conditional

- .github/workflows/acc-tests.yaml
Dug my old hackathon project of having a shared acceptance tests workflow that can be reused across all plugins that adopted the [proposed set of make targets](https://docs.google.com/document/d/1Gz0DohBnmH2WaqrQA3JCix_m6ISVyX56nYMDdT5worM/edit?usp=sharing) to standardize how to bootstrap and test plugins locally.
Here is an [example of converting a project](https://github.com/hashicorp/vault-plugin-database-redis/pull/47) (Redis plugin) to the shared pattern & using this workflow to run acc tests on all pull requests.
This workflow will likely need a lot of improvements over time to be more robust, faster and support different plugin setups but it's a start towards more automation.
> Acctest reusable flow

- .github/workflows/jira.yaml
Sometimes there are GitHub issues we do not plan to take on internally but do not want to close. For example:
* The issue is not actionable but has a lot of great context in the discussion that could help others
* The issue is a good idea but not impactful enough to justify the amount of work to take it on internally, but we'd gladly accept a pull request
* The issue needs more info to be actionable but the contributor is MIA
* etc.
These issues pile in our backlogs making it harder for teams to prioritise their work. We'd like to suggest that Jira tickets for unactionable GitHub issues should be iceboxed. We should still comment on the issue to let the contributor know that we do not plan to address the issue ourselves and why to set the correct expectations.
A new step is added to thaw …
> Thaw iceboxed jira ticket if there is a new comment

- .github/workflows/go-checks.yaml
Hopefully this will allow us to use the security-scanner action. See failure here: https://github.com/hashicorp/vault-plugin-auth-alicloud/actions/runs/7629816189/job/20784103686
> add token to security scanner go check

- .github/workflows/go-checks.yaml
The Github Action interpreter currently doesn't identify the secrets key word when used in an if conditional expression. Need to have a separate step to check for availability.
> fix go-checks secret check

- .github/workflows/go-checks.yaml
Attempting to fix `Error: Unable to resolve action hashicorp/security-scanner, repository not found` example: https://github.com/hashicorp/vault-plugin-database-snowflake/actions/runs/7729128525/job/21117747597
> sec scanner: set gh token at job level

- .github/workflows/bulk-dependency-updates.yaml
Useful for Oracle and other non-builtin plugins. Test run https://github.com/hashicorp/vault-plugin-database-oracle/actions/runs/7758370586/job/21159987307
> bulk updates: add skip vault ci input

- repo-teams.txt
We will let the plugin set its own labels since it requires `foundations` and `storage`. For now our override logic doesn't account for multiple labels.
Related to https://github.com/hashicorp/vault-plugin-secrets-kv/pull/162
> remove kv plugin from team override

- .github/workflows/jira.yaml
Since $teams_field will always be set to at least `[""]`.
> If $label is empty use the input teams

- .github/workflows/jira.yaml
Use [gh-action-jira-search@v0.3.1](https://github.com/hashicorp/gh-action-jira-search/releases/tag/v0.3.1) to pickup the new search API URL.
> use v0.3.1 of jira search
